name: "Deploy to S3"
description: "Deploy build artifacts to S3"

inputs:
  app-type:
    description: "Type of application"
    required: true
  app-id:
    description: "ID of the application"
    required: true
  config-path:
    description: "Path to config.json"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-south-1

    - name: Get S3 bucket from SSM
      id: ssm
      shell: bash
      run: |
        PREFIX="/hosting-template/frontend"

        BUCKET_PARAM="${PREFIX}/bucket"
        BUCKET=$(aws ssm get-parameter \
          --name "$BUCKET_PARAM" \
          --query 'Parameter.Value' \
          --output text 2>/dev/null || echo "")

        if [ -z "$BUCKET" ]; then
          echo "::error::Could not find S3 bucket at $BUCKET_PARAM"
          exit 1
        fi

        echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
        echo "region=ap-south-1" >> $GITHUB_OUTPUT

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.app-type }}-${{ inputs.app-id }}
        path: ./deploy

    - name: Deploy to S3
      shell: bash
      run: |
        aws s3 sync \
          ./deploy \
          s3://${{ steps.ssm.outputs.bucket }} \
          --delete \
          --acl public-read \
          --cache-control "public, max-age=31536000, immutable"
