name: "Deploy Frontend to S3"
description: "Sync built frontend to S3 bucket"

inputs:
  directory:
    required: true
  bucket:
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload files to S3
      shell: bash
      run: |
        aws s3 sync "${{ inputs.directory }}" "s3://${{ inputs.bucket }}" --delete
